language: go

jobs:
  include:
    - os: linux
      go: "1.13.x"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: linux
      go: "1.14.x"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: linux
      go: "1.15.x"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go: "1.15.x"
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod

    - os: windows
      go: "1.15.x"
      cache:
        directories:
          - $USERPROFILE/AppData/Local/go-build
          - $USERPROFILE/gopath/pkg/mod


install:
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - go build -v .
  - go test -v -race -short -coverprofile=coverage.txt ./...

after_success:
  - if [ -f coverage.txt ]; then bash <(curl -s https://codecov.io/bash); fi
