baseURL = 'https://creativeprojects.github.io/resticprofile/'
# this is needed because the site is installed in a subdirectory
canonifyURLs = true
languageCode = 'en-gb'
title = 'resticprofile'
theme = "hugo-theme-relearn"
publishdir = "../public/"

# For search functionality
[outputs]
  home = [ "html", "rss" ]

[params]
  # themeVariant = [ "relearn-dark", "relearn-light"  ]
  themeVariant = [
    { identifier = 'relearn-auto',  name = 'Relearn Light/Dark', auto = [] },
    { identifier = 'relearn-light'  },
    { identifier = 'relearn-dark'   },
  ]
  collapsibleMenu = true
  externalLinkTarget = "_blank"
  ordersectionsby = "weight"

[[menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "/tags"
  weight = 10

[[menu.shortcuts]]
  name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
  identifier = "ds"
  url = "https://github.com/creativeprojects/resticprofile/"
  weight = 20

[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-bookmark'></i> Restic Documentation"
  identifier = "resticdoc"
  url = "https://restic.readthedocs.io/"
  weight = 30

[markup]
  [markup.highlight]
    # line numbers in a table layout will shift if code is wrapping, so better
    # use inline; besides that visually both layouts have the same look and behavior
    lineNumbersInTable = false

    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid or Math codefences
    guessSyntax = false

    # the shipped variants come with their own modified chroma syntax highlightning
    # style which is imported in theme-relearn-light.css, theme-relearn-dark.css, etc.;
    # if you want to use a predefined style instead:
    # - remove `noClasses` or set `noClasses = true`
    # - set `style` to a predefined style name
    noClasses = false
    # style = "tango"
